apps/agency/urls.py
from django.conf.urls import url
from apps.agency import views

app_name = 'agency'


urlpatterns = [
    url(r'novo/$',
        views.NewAgency.as_view(), name='new'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateAgency.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteAgency.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailAgency.as_view(), name='detail'),
    url(r'$', views.ListAgency.as_view(), name='list'),
]

apps/client/urls.py
from django.conf.urls import url
from apps.client import views

app_name = 'client'

urlpatterns = [
    url(r'novo/$',
        views.NewClient.as_view(), name='new'),
    url(r'email/$',
        views.ClientAjaxEmail.as_view(), name='email'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateClient.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteClient.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailClient.as_view(), name='detail'),
    url(r'$', views.ListClient.as_view(), name='list'),
]

apps/outdoor/urls.py
from django.conf.urls import url
from apps.outdoor import views

app_name = 'outdoor'

urlpatterns = [
    url(r'novo/$',
        views.NewOutdoor.as_view(), name='new'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateOutdoor.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteOutdoor.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/email/add/$',
        views.OutdoorEmailAdd.as_view(), name='email'),
    url(r'(?P<pk>[\w_-]+)/email/clear/one/$',
        views.OutdoorEmailClearOne.as_view(), name='email-clear-one'),

    url(r'email/clear/all/$',
        views.OutdoorEmailClearAll.as_view(), name='email-clear'),

    url(r'email/send/$',
        views.OutdoorEmailSend.as_view(), name='email-send'),

    url(r'(?P<pk>[\w_-]+)/locar/$',
        views.LocaOutdoor.as_view(), name='locar'),

    url(r'(?P<pk>[\w_-]+)/convert/$',
        views.Convert.as_view(), name='convert'),


    url(r'(?P<pk>[\w_-]+)/reserva/$',
        views.ReserveOutdoor.as_view(), name='reserva'),

    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailOutdoor.as_view(), name='detail'),
    url(r'$', views.ListOutdoor.as_view(), name='list'),
]

apps/rent/urls.py
from django.conf.urls import url
from apps.rent import views

app_name = 'rent'

urlpatterns = [
    url(r'novo/$',
        views.NewLocation.as_view(), name='new'),
    url(r'(?P<pk>[\w_-]+)/editar/$',
        views.UpdateLocation.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteLocation.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailLocation.as_view(), name='detail'),
    url(r'$',
        views.ListLocation.as_view(), name='list'),
]

floriano_outdoor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from apps.client import urls as client_urls
from apps.core import urls as core_urls
from apps.agency import urls as agency_urls
from apps.outdoor import urls as outdoors_urls
from apps.rent import urls as rent_urls
from apps.usuarios import urls as users_urls
from apps.reserve import urls as reserve_urls
from apps.cash import urls as cash_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^clientes/', include(client_urls)),
    url(r'^agencias/', include(agency_urls)),
    url(r'^outdoors/', include(outdoors_urls)),
    url(r'^locacao/', include(rent_urls)),
    url(r'^usuarios/', include(users_urls)),
    url(r'^reservas/', include(reserve_urls)),
    url(r'^caixa/', include(cash_urls)),
    url(r'^', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/rent/models.py
from django.db import models
from apps.core.models import SuperClass


class Location(SuperClass):

    client = models.ForeignKey(
        'client.Client', blank=True, null=True, related_name='client_location')
    agency = models.ForeignKey(
        'agency.Agency', blank=True, null=True, related_name='agency_location')

    outdoor = models.ForeignKey(
        'outdoor.Outdoor',
        blank=True, null=True, related_name='outdoor_location')

    start = models.DateField('Início', null=True, blank=True)
    end = models.DateField('Fim', null=True, blank=True)

    creator = models.ForeignKey(
        'auth.User', blank=True, null=True, related_name='creator_location')

    class Meta:
        verbose_name = "Locação"
        verbose_name_plural = "Locações"
        ordering = ('start',)
        get_latest_by = '-created_at'

    def __str__(self):
        return "Locacao outdoor %d" % self.outdoor.id

apps/rent/forms.py
from django import forms
from apps.client.models import Client
from apps.agency.models import Agency
from apps.outdoor.models import Outdoor
from django.conf import settings
from django.db.models import Q
import datetime


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + datetime.timedelta(n)


class FormLocation(forms.Form):
    outdoor = forms.ModelChoiceField(
        label='Outdoor', queryset=Outdoor.objects.all(),  required=True,
        widget=forms.Select(attrs={'class': ''}))
    client = forms.ModelChoiceField(
        label='Cliente', queryset=Client.objects.all(),  required=True,
        widget=forms.Select(attrs={'class': ''}))
    agency = forms.ModelChoiceField(
        label='Agencia', queryset=Agency.objects.all(),  required=False,
        widget=forms.Select(attrs={'class': ''}))

    start = forms.DateField(
        label='Inicio', input_formats=settings.DATE_INPUT_FORMATS,
         required=True,
        widget=forms.DateInput(attrs={'class': 'datepicker'}))
    end = forms.DateField(
        label='Fim', input_formats=settings.DATE_INPUT_FORMATS,
        required=True,
        widget=forms.DateInput(attrs={'class': 'datepicker'}))
    location = forms.IntegerField(
        label='', widget=forms.HiddenInput(), initial='', required=False)

    alert = forms.BooleanField(
        label='Aleta de Email', required=False, initial=False,
        widget=forms.CheckboxInput(attrs={'class': ''}))

    # cash
    cash = forms.BooleanField(
        label='Caixa', required=False, initial=False,
        widget=forms.CheckboxInput(attrs={'class': ''}))
    date = forms.DateField(
        label='Data', required=False,
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(
            attrs={'class': 'datepicker', 'readonly': True}))
    value = forms.DecimalField(
        label='Valor', required=False,
        widget=forms.NumberInput(attrs={'class': ''}))
    observation = forms.CharField(
        label='Descrição', required=False,
        widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))

    def clean(self):
        cleaned_data = super(FormLocation, self).clean()
        today = datetime.date.today()
        data_start = cleaned_data['start']
        data_end = cleaned_data['end']
        outdoor = cleaned_data['outdoor']
        location_id = cleaned_data['location']

        if data_start >= data_end:
            self.add_error(
                'start', "Data de início menor que data final")
        # elif today <= data_start:
        #     self.add_error(
        #         'start_date', "Data de início menor que data atual")
        else:
            ex = Q()
            if location_id:
                ex.add(Q(id=location_id), Q.AND)
            for check_date in daterange(data_start, data_end):
                query = Q(status=True)
                query.add(
                    Q(start__lte=check_date) & Q(end__gte=check_date), Q.AND)
                if outdoor.outdoor_location.filter(query).exclude(ex).exists():
                    self.add_error('end', "Outdoor locado nessa data")
                    break

            for check_date in daterange(data_start, data_end):
                query = Q(status=True)
                query.add(
                    Q(start__lte=check_date) & Q(end__gte=check_date), Q.AND)
                if outdoor.outdoor_reserve.filter(query).exists():
                    self.add_error('end', "Outdoor reservado nessa data")
                    break


class FormSearchLocation(forms.Form):
    term = forms.CharField(
        label='Busca', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    start = forms.DateField(
        label='Inicio', input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': 'datepicker'}))
    end = forms.DateField(
        label='Fim', input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': 'datepicker'}))

apps/rent/views.py
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .forms import FormLocation, FormSearchLocation
from apps.rent.models import Location
from apps.cash.models import Movement
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from datetime import datetime
from django.contrib import messages


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self)\
            .dispatch(request, *args, **kwargs)


class DeleteLocation(LoginRequiredMixin, DeleteView):
    model = Location
    success_url = reverse_lazy('rent:list')
    template_name = 'rent/delete.html'
    success_message = 'Locação deletada com sucesso'
    slug_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super(DeleteLocation, self).get_context_data(**kwargs)
        context.update(dict(
            title='Deletar Locação',
            link_list=self.success_url, list="Locações"))
        return context


class DetailLocation(LoginRequiredMixin, DetailView):
    slug_field = 'id'
    model = Location
    context_object_name = 'object'
    template_name = "rent/detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailLocation, self).get_context_data(**kwargs)
        context.update(dict(
            title='Detalhe Locação',
            link_list=reverse_lazy('rent:list'), list="Locações"))
        return context


class NewLocation(LoginRequiredMixin, FormView):
    template_name = 'rent/form.html'
    form_class = FormLocation
    success_url = reverse_lazy('rent:list')

    def get_context_data(self, **kwargs):
        context = super(NewLocation, self).get_context_data(**kwargs)
        # context.update(dict(msg=self.request.GET.get('msg', None)))
        context.update(dict(
            title='Locar Outdoor',
            link_list=self.success_url, list="Locações"))
        return context

    def form_valid(self, form):
        data = form.cleaned_data

        location = Location(
            client=data['client'],
            agency=data['agency'],
            start=data['start'],
            outdoor=data['outdoor'],
            end=data['end']
        )

        location.save()

        if data['cash']:
            movement = Movement(
                history=location.client.name,
                kind='RE',
                date=data['date'],
                value=data['value'],
                close=False,
                observation=data['observation'],
            )

            movement.save()

        if data['alert']:
            outdoors = [{'outdoor': location.outdoor, 'price': None}, ]
            ctx = {
                'outdoors': outdoors,
                'title': 'Locação de outdoor',
                'text': '''
                    Olá %s, segue foto do outdoor que você acacou de locar
                    no periodo de %s à %s.
                ''' % (
                        location.client.name,
                        location.start.strftime('%d/%m/%Y'),
                        location.end.strftime('%d/%m/%Y')
                    )
            }
            msg_html = render_to_string(
                'core/email.html', ctx)
            msg_plain = strip_tags(msg_html)
            send_mail(
                "Locação de outdoor",
                msg_plain,
                settings.EMAIL_HOST_USER,
                [location.client.email],
                html_message=msg_html,
            )

        msg = "Locação cadastrada com sucesso!"
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(NewLocation, self).form_valid(form)

    def form_invalid(self, form):
        for key in form.errors:
            if key != '__all__':
                msg = '%s - %s' % (form[key].label, form.errors[key].as_text())
                messages.add_message(self.request, messages.WARNING, msg)
        return super(NewLocation, self).form_invalid(form)


class ListLocation(LoginRequiredMixin, ListView):
    template_name = "rent/list.html"
    model = Location
    context_object_name = 'locations'
    paginate_by = 15

    def get_queryset(self, **kwargs):
        query = Q(status=True)

        if self.request.GET.get('start', None):
            start = datetime.strptime(self.request.GET['start'], '%d/%m/%Y')
            query.add(Q(start__gte=start), Q.AND)

        if self.request.GET.get('end', None):
            end = datetime.strptime(self.request.GET['end'], '%d/%m/%Y')
            query.add(Q(end__lte=end), Q.AND)

        if self.request.GET.get('term', None):
            query.add(
                Q(outdoor__code__icontains=self.request.GET['term']) |
                Q(agency__name__icontains=self.request.GET['term']) |
                Q(client__name__icontains=self.request.GET['term']), Q.AND)

        return Location.objects.filter(query).order_by('-end')

    def get_context_data(self, **kwargs):
        context = super(ListLocation, self).get_context_data(**kwargs)
        context['form_search'] = FormSearchLocation(
            initial=self.request.GET.dict())
        context.update(dict(
            link_list=reverse_lazy('rent:list'),
            list="Locações"
            ))
        return context


class UpdateLocation(LoginRequiredMixin, FormView):
    template_name = 'rent/form.html'
    form_class = FormLocation
    success_url = reverse_lazy('rent:list')

    def get_location(self):
        return get_object_or_404(Location, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super(UpdateLocation, self).get_context_data(**kwargs)
        l = self.get_location()

        context['form'] = FormLocation(initial=l.__dict__)

        context['form'].fields["location"].initial = l.id

        if l.agency:
            context['form'].fields["agency"].initial = l.agency.id

        if l.outdoor:
            context['form'].fields["outdoor"].initial = l.outdoor.id

        if l.client:
            context['form'].fields["client"].initial = l.client.id

        # context.update(dict(msg=self.request.GET.get('msg', None)))
        context.update(dict(
            title='Editar locação %s - %s' % (l.client.name, l.outdoor.code),
            link_list=self.success_url,
            list="Clientes"
        ))
        return context

    def form_valid(self, form):
        data = form.cleaned_data

        location = self.get_location()

        location.client = data['client']
        location.agency = data['agency']
        location.start = data['start']
        location.outdoor = data['outdoor']
        location.end = data['end']

        location.save()

        msg = "Locação alterada com sucesso!"
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(UpdateLocation, self).form_valid(form)

    def form_invalid(self, form):
        for key in form.errors:
            if key != '__all__':
                msg = '%s - %s' % (form[key].label, form.errors[key].as_text())
                messages.add_message(self.request, messages.WARNING, msg)
        return super(UpdateLocation, self).form_invalid(form)

apps/rent/templates/rent/delete.html
{% extends "components/base.html" %}

{% block content %}

  <div class="row">
    <div class="col s12 m12 l12">
      <h3>Você deseja deletar a locação  "{{ object }}" ?</h3>
      <form method="post" action="">
        {% csrf_token %}
        <br>
        <div class="row">
          <a class="btn red" href="{% url 'rent:list' %}">
            <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
          </a>
          <button type="submit" value="" class="btn green" >
            <i class="fa fa-fw fa-trash" aria-hidden="true"></i> Deletar
          </button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/rent/templates/rent/detail.html
{% extends "components/base.html" %}

{% block content %}


<div class="row">
  <div class="col s12 m12 l6">

    <ul class="collection z-depth-1">
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">assignment_ind</i> Cliente</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.client.name}}</div>
        </div>
      </li>

      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">date_range</i> Período</div>
          <div class="col s7 grey-text text-darken-4 right-align"><td>{{object.start|date:"d/m/y"}} - {{object.end|date:"d/m/y"}}</td></div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">location_city</i> Agencia</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.agency.name}}</div>
        </div>
      </li>

    </ul>


  </div>

  <div class="col s12 m12 l6">
    <div class="card">
      <div class="card-image">
        <img src="{% if object.outdoor.image %}{{object.outdoor.image.url}}{% else %}/static/img/outdoor.png{% endif %}">
        <span class="card-title">{{object.outdoor.code}}</span>
      </div>
      <div class="card-content">
        <p><b>Cidade:</b> {{object.outdoor.cidade}}</p>
        <p><b>Bairro:</b> {{object.outdoor.bairro}}</p>
        <p><b>Referencia:</b> {{object.outdoor.referencia}}</p>
      </div>
      <div class="card-action">
        {# <a href="#">This is a link</a>#}
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extra_js %}

{% endblock %}

apps/rent/templates/rent/form.html
{% extends "components/base.html" %}

{% block content %}

<div class="row">

  <div class="col s12 m8 l6">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <div class="row">
          {% if field.field.widget.input_type == 'file' %}
            <div class="file-field input-field col s12 m12 l6 col">
              <div class="btn">
                <span>{{field.label}}</span>
                {{field}}
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
              </div>
            </div>
          {% elif field.field.widget.input_type == 'checkbox' %}
            <div class="col s12 m12 l6">
              {{field}}
              <label for="{{field.auto_id}}">
                {{field.label}}
              </label>
            </div>
          {% else %}
            <div class="input-field col s12 m12 l12">
              {{field}}
              <label for="email" data-error="wrong" data-success="right">
                {{field.label}}
              </label>
            </div>
          {% endif %}

          {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
      {% endfor%}
      <br>
      <div class="row">
        <div class="input-field col s12 m12 l12">
        <a class="btn red" href="{% url 'rent:list' %}">
          <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
        </a>
        <button type="submit" class="btn green">
          <i class="fa fa-fw fa-floppy-o" aria-hidden="true"></i> Locar
        </button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

{% block extra_js %}

  <script>

    $('.datepicker').pickadate({
      selectMonths: true, // Creates a dropdown to control month
      selectYears: 15, // Creates a dropdown of 15 years to control year,
      today: 'Hoje',
      clear: 'Limpar',
      close: 'Fechar',
      closeOnSelect: false, // Close upon selecting a date,
      format: 'dd/mm/yyyy',
      formatSubmit: 'dd/mm/yyyy',
      onClose: function() {
        $(document.activeElement).blur();
        console.log('close');
      }
    });

    $('#id_end').change(function(){
      // var parts_s $('#id_start').val().split('/');
      // var parts_e ='04/03/2014'.split('/');
      // var mydate = new Date(parts[2],parts[0]-1,parts[1]);
    });

    $('#id_cash').change(function(){
      if ($('#id_cash').is(":checked")) {
        $('#id_date').parent().show();
        $('#id_value').parent().show();
        $('#id_observation').parent().show();
      } else {
        $('#id_date').val('');
        $('#id_date').parent().hide();
        $('#id_value').val('');
        $('#id_value').parent().hide();
        $('#id_observation').val('');
        $('#id_observation').parent().hide();
      }
    });

    $('#id_cash').trigger('change');

  </script>

{% endblock %}

apps/rent/templates/rent/list.html
{% extends "components/base.html" %}

{% load outdoor_tags %}

{% block content %}

  <div class="row">
    <form action="" method="get">
      <div class="row">
        {% for field in form_search %}
          <div class="input-field col s12 m3 l4">
            {{field}}
            <label for="{{field.auto_id}}">{{field.label}}</label>
          </div>
        {% endfor %}
      </div>
      <div class="input-field col s12 m3 l4">
        <button type="submit" class="btn green">
          <i class="fa fa-fw fa-search-o" aria-hidden="true"></i> Buscar
        </button>
      </div>
    </form>
  </div>


  <div class="row">
    <div class="col l12 m12 s12">
      <div class="table-responsive">
        <table class="table table-striped responsive-table">
          <thead>
            <tr>
              <th>Cliente</th>
              <th>Agência</th>
              <th>Outdoor</th>
              <th>Inicio</th>
              <th>Fim</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
              {% for l in locations %}
              <tr>
                {% if l.client %}
                  <td><a href="{% url 'client:detail' l.client.id %}">{{l.client.name}}</a></td>
                {% else %}
                  <td><a href="#">Sem cliente</a></td>
                {% endif %}
                {% if l.agency %}
                <td><a href="{% url 'agency:detail' l.agency.id %}">{{l.agency.name}}</a></td>
                {% else %}
                  <td><a href="#">Sem agencia</a></td>
                {% endif %}
                <td><a href="{% url 'outdoor:detail' l.outdoor.id %}">{{l.outdoor.code}}</a></td>
                <td>{{l.start|date:"d/m/y"}}</td>
                <td>{{l.end|date:"d/m/y"}}</td>
                <td>
                  <div class="btn-group btn-group-sm" role="group" aria-label="...">
                  <a href="{% url 'rent:detail' l.id %}" class="btn">
                    <i class="material-icons">remove_red_eye</i>
                  </a>
                  <a href="{% url 'rent:edit' l.id %}" class="btn yellow">
                    <i class="material-icons">mode_edit</i>
                  </a>
                  <a href="{% url 'rent:delete' l.id %}" class="btn red">
                    <i class="material-icons">clear</i>
                  </a>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row">

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="waves-effect" ><a href="?{% url_replace page=page_obj.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
      {% else %}
        <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}

        <li class="">
            <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
        </li>

      {% if page_obj.has_next %}
          <li class="waves-effect"><a href="?{% url_replace page=page_obj.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
      {% else %}
        <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
      {% endif %}
    </ul>
  {% endif %}
  </div>


  <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">

    <a class="btn-floating btn-large waves-effect waves-light pink" href="{% url 'rent:new' %}"><i class="material-icons">add</i></a>
  </div>

  {% comment %}


  <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large pink waves-effect waves-light">
      <i class="large material-icons">add</i>
    </a>

    <ul>
      <li>
        <a class="btn-floating red"><i class="material-icons">note_add</i></a>
        <a href="" class="btn-floating fab-tip">Add a note</a>
      </li>

      <li>
        <a class="btn-floating yellow darken-1"><i class="material-icons">add_a_photo</i></a>
        <a href="" class="btn-floating fab-tip">Add a photo</a>
      </li>

      <li>
        <a class="btn-floating green"><i class="material-icons">alarm_add</i></a>
        <a href="" class="btn-floating fab-tip">Add an alarm</a>
      </li>

      <li>
        <a class="btn-floating blue"><i class="material-icons">vpn_key</i></a>
        <a href="" class="btn-floating fab-tip">Add a master password</a>
      </li>
    </ul>
  </div>

  {% endcomment %}
{% endblock %}


{% block extra_js %}

  <script>
    $(document).ready(function() {
    });

    $('.datepicker').pickadate({
       selectMonths: true, // Creates a dropdown to control month
       selectYears: 15, // Creates a dropdown of 15 years to control year,
       today: 'Today',
       clear: 'Clear',
       close: 'Ok',
       closeOnSelect: false, // Close upon selecting a date,
       format: 'dd/mm/yyyy',
     });
  </script>

{% endblock %}