apps/agency/urls.py
from django.conf.urls import url
from apps.agency import views

app_name = 'agency'


urlpatterns = [
    url(r'novo/$',
        views.NewAgency.as_view(), name='new'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateAgency.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteAgency.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailAgency.as_view(), name='detail'),
    url(r'$', views.ListAgency.as_view(), name='list'),
]

apps/client/urls.py
from django.conf.urls import url
from apps.client import views

app_name = 'client'

urlpatterns = [
    url(r'novo/$',
        views.NewClient.as_view(), name='new'),
    url(r'email/$',
        views.ClientAjaxEmail.as_view(), name='email'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateClient.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteClient.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailClient.as_view(), name='detail'),
    url(r'$', views.ListClient.as_view(), name='list'),
]

apps/outdoor/urls.py
from django.conf.urls import url
from apps.outdoor import views

app_name = 'outdoor'

urlpatterns = [
    url(r'novo/$',
        views.NewOutdoor.as_view(), name='new'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateOutdoor.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteOutdoor.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/email/add/$',
        views.OutdoorEmailAdd.as_view(), name='email'),
    url(r'(?P<pk>[\w_-]+)/email/clear/one/$',
        views.OutdoorEmailClearOne.as_view(), name='email-clear-one'),

    url(r'email/clear/all/$',
        views.OutdoorEmailClearAll.as_view(), name='email-clear'),

    url(r'email/send/$',
        views.OutdoorEmailSend.as_view(), name='email-send'),

    url(r'(?P<pk>[\w_-]+)/locar/$',
        views.LocaOutdoor.as_view(), name='locar'),

    url(r'(?P<pk>[\w_-]+)/convert/$',
        views.Convert.as_view(), name='convert'),


    url(r'(?P<pk>[\w_-]+)/reserva/$',
        views.ReserveOutdoor.as_view(), name='reserva'),

    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailOutdoor.as_view(), name='detail'),
    url(r'$', views.ListOutdoor.as_view(), name='list'),
]

floriano_outdoor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from apps.client import urls as client_urls
from apps.core import urls as core_urls
from apps.agency import urls as agency_urls
from apps.outdoor import urls as outdoors_urls
from apps.rent import urls as rent_urls
from apps.usuarios import urls as users_urls
from apps.reserve import urls as reserve_urls
from apps.cash import urls as cash_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^clientes/', include(client_urls)),
    url(r'^agencias/', include(agency_urls)),
    url(r'^outdoors/', include(outdoors_urls)),
    url(r'^locacao/', include(rent_urls)),
    url(r'^usuarios/', include(users_urls)),
    url(r'^reservas/', include(reserve_urls)),
    url(r'^caixa/', include(cash_urls)),
    url(r'^', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/client/models.py
from django.db import models
from apps.core.models import SuperClass


class Client(SuperClass):
    name = models.CharField(
        "Nome", max_length=255, null=False, blank=False)
    cpf = models.CharField(
        "CPF", max_length=255, null=False, blank=False)
    rg = models.CharField(
        "RG", max_length=255, null=False, blank=False)
    fone = models.CharField(
        "Telefone", max_length=255, null=True, blank=True)
    email = models.CharField(
        "Email", max_length=255, null=True, blank=True)
    brith = models.DateField('Nascimento', null=True, blank=True)
    observation = models.TextField("Texto", null=True, blank=True)
    cidade = models.CharField(
        "Cidade", max_length=255, null=True, blank=True)
    bairro = models.CharField(
        "Bairro", max_length=255, null=True, blank=True)
    rua = models.CharField(
         "Rua", max_length=255, null=True, blank=True)
    numero = models.CharField(
         "Número", max_length=255, null=True, blank=True)
    cep = models.CharField(
         "CEP", max_length=255, null=True, blank=True)
    creator = models.ForeignKey(
        'auth.User', blank=True, null=True, related_name='creator_client')

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ('name',)
        get_latest_by = '-created_at'

    def __str__(self):
        return self.name

apps/client/forms.py
from django import forms
from django.conf import settings


class FormClient(forms.Form):
    name = forms.CharField(
        label='Nome', max_length=80, required=True,
        widget=forms.TextInput(attrs={'class': ''}))
    cpf = forms.CharField(
        label='CPF', max_length=80, required=True,
        widget=forms.TextInput(attrs={'class': ''}))
    rg = forms.CharField(
        label='RG', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    fone = forms.CharField(
        label='Telefone', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    email = forms.CharField(
        label='Email', max_length=80, required=True,
        widget=forms.TextInput(attrs={'class': ''}))
    brith = forms.DateField(
        label='Nascimento', input_formats=settings.DATE_INPUT_FORMATS,
        required=False, widget=forms.DateInput(attrs={'class': ''}))
    cidade = forms.CharField(
        label='Cidade', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    bairro = forms.CharField(
        label='Bairro', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    rua = forms.CharField(
        label='Rua', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    numero = forms.CharField(
        label='Número', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    cep = forms.CharField(
        label='CEP', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    observation = forms.CharField(
        label='Descrição', required=False,
        widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))


class FormSearchClient(forms.Form):
    term = forms.CharField(
        label='Busca', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))

apps/client/views.py
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .forms import FormClient, FormSearchClient
from .models import Client
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import View
from django.http import HttpResponse
import json


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self)\
            .dispatch(request, *args, **kwargs)


class DeleteClient(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client:list')
    template_name = 'client/delete.html'
    success_message = 'Cliente deletado com sucesso'
    slug_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super(DeleteClient, self).get_context_data(**kwargs)
        context.update(dict(
            title='Deletar Cliente',
            link_list=self.success_url, list="Clientes"))
        return context


class DetailClient(LoginRequiredMixin, DetailView):
    slug_field = 'id'
    model = Client
    context_object_name = 'object'
    template_name = "client/detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailClient, self).get_context_data(**kwargs)
        context.update(dict(
            title='Detalhe Cliente',
            link_list=reverse_lazy('client:list'), list="Clientes"))
        return context


class NewClient(LoginRequiredMixin, FormView):
    template_name = 'client/form.html'
    form_class = FormClient
    success_url = reverse_lazy('client:list')

    def get_context_data(self, **kwargs):
        context = super(NewClient, self).get_context_data(**kwargs)
        context.update(dict(
            title='Novo Cliente',
            link_list=self.success_url,
            list="Clientes"
            ))
        return context

    def form_valid(self, form):
        data = form.cleaned_data

        client = Client(
            name=data['name'],
            cpf=data['cpf'],
            email=data['email'],
            fone=data['fone'],
            rg=data['rg'],
            brith=data['brith'],
            observation=data['observation'],
            cidade=data['cidade'],
            bairro=data['bairro'],
            rua=data['rua'],
            numero=data['numero'],
            cep=data['cep'],
        )

        client.save()

        msg = "Cliente adicionado com sucesso!"
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(NewClient, self).form_valid(form)


class ListClient(LoginRequiredMixin, ListView):
    template_name = "client/list.html"
    model = Client
    context_object_name = 'clients'
    paginate_by = 10

    def get_queryset(self, **kwargs):
        query = Q(status=True)

        if self.request.GET.get('term', None):
            query.add(
                Q(name__icontains=self.request.GET['term']) |
                Q(cpf__icontains=self.request.GET['term']) |
                Q(observation__icontains=self.request.GET['term']) |
                Q(cidade__icontains=self.request.GET['term']) |
                Q(bairro__icontains=self.request.GET['term']) |
                Q(email__icontains=self.request.GET['term']), Q.AND)

        return Client.objects.filter(query)

    def get_context_data(self, **kwargs):
        context = super(ListClient, self).get_context_data(**kwargs)
        context['form_search'] = FormSearchClient(
            initial=self.request.GET.dict())
        context.update(dict(
            link_list=reverse_lazy('client:list'),
            list="Clientes"
            ))
        return context


class UpdateClient(LoginRequiredMixin, FormView):
    template_name = 'client/form.html'
    form_class = FormClient
    success_url = reverse_lazy('client:list')

    def get_client(self):
        return get_object_or_404(Client, id=self.kwargs.get('id'))

    def get_context_data(self, **kwargs):
        context = super(UpdateClient, self).get_context_data(**kwargs)
        c = self.get_client()
        context['form'] = FormClient(initial=c.__dict__)
        # context.update(dict(msg=self.request.GET.get('msg', None)))
        context.update(dict(
            title='Editar %s' % c.name,
            link_list=self.success_url,
            list="Clientes"
        ))
        return context

    def form_valid(self, form):
        data = form.cleaned_data

        client = self.get_client()

        client.name = data['name']
        client.email = data['email']
        client.cpf = data['cpf']
        client.fone = data['fone']
        client.rg = data['rg']
        client.brith = data['brith']
        client.observation = data['observation']
        client.cidade = data['cidade']
        client.bairro = data['bairro']
        client.rua = data['rua']
        client.numero = data['numero']
        client.cep = data['cep']

        client.save()

        msg = "Cliente alterado com sucesso!"
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(UpdateClient, self).form_valid(form)


class ClientAjaxEmail(View):

    def get(self, request, *args, **kwargs):
        clients = Client.objects.all()
        res = [{'%s - %s' % (c.name, c.email): None} for c in clients]
        return HttpResponse(json.dumps(res), content_type='application/json')

apps/client/templates/client/delete.html
{% extends "components/base.html" %}

{% block content %}

  <div class="row">
    <div class="col s12 m12 l12">
      <h3>Você deseja deletar o cliente  "{{ object.name }}" ?</h3>
      <form method="post" action="">
        {% csrf_token %}
        <br>
        <div class="row">
          <a class="btn red" href="{% url 'client:list' %}">
            <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
          </a>
          <button type="submit" value="" class="btn green" >
            <i class="fa fa-fw fa-trash" aria-hidden="true"></i> Deletar
          </button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/client/templates/client/detail.html
{% extends "components/base.html" %}

{% block content %}


<div class="row">
  <div class="col s12 m12 l6">

    <ul class="collection z-depth-1">
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">assignment_ind</i> Nome</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.name}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">assignment_ind</i> CPF</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.cpf}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">assignment_ind</i> RG</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.rg}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">contact_mail</i> Email</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.email}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">contact_phone</i> Telefone</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.fone}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">date_range</i> Nascimento</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.brith | date:'d/m/Y'}} </div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">location_city</i> Cidade</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.cidade}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">location_city</i> Bairro</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.bairro}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">location_city</i> Rua</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.rua}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">location_city</i> Numero</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.numero}}</div>
        </div>
      </li>
      <li class="collection-item">
        <div class="row valign-wrappe">
          <div class="col s5 grey-text darken-1"><i class="material-icons">location_city</i> CEP</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.cep}}</div>
        </div>
      </li>

      <li class="collection-item">
        <div class="row">
          <div class="col s5 grey-text darken-1"><i class="material-icons">event_note</i> Observação</div>
          <div class="col s7 grey-text text-darken-4 right-align">{{object.observation}}</div>
        </div>
      </li>


    </ul>


  </div>

  <div class="col s12 m12 l6">
      <h4>Locações</h4>

      <table class="table table-condensed table-hover" id='table_service'>
        <thead>
          <tr>
            <th>Agência</th>
            <th>Outdoor</th>
            <th>Inicio</th>
            <th>Fim</th>
          </tr>
        </thead>
        <tbody>
          {% for l in object.client_location.all %}
          <tr>
            <td><a href="{% url 'agency:detail' l.agency.id %}">{{l.agency.name}}</a></td>
            <td><a href="{% url 'outdoor:detail' l.outdoor.id %}">{{l.outdoor.code}}</a></td>
            <td>{{l.start|date:"d/m/y"}}</td>
            <td>{{l.end|date:"d/m/y"}}</td>
          </tr>
          {% empty %}
            <tr>
              <td colspan="4"> Sem Cadastros</td>
            </tr>
          {% endfor %}
        </tbody>
        <tfoot>
        </tfoot>
      </table>

      <h5>Reservas</h5>
      <table class="table table-condensed table-hover" id='table_service'>
        <thead>
          <tr>
            <th>Agência</th>
            <th>Outdoor</th>
            <th>Periodo</th>
          </tr>
        </thead>
        <tbody>
          {% for loc in  object.client_reserve.all|slice:":10" %}
          <tr>
            <td>{{loc.agency.name}}</td>
            <td>{{loc.outdoor.code}}</td>
            <td>{{loc.start|date:"d/m/y"}} - {{loc.end|date:"d/m/y"}}</td>
          </td>
          {% endfor %}

        </tbody>
        <tfoot>
        </tfoot>
      </table>
  </div>
</div>

{% endblock %}

{% block extra_js %}

{% endblock %}

apps/client/templates/client/form.html
{% extends "components/base.html" %}

{% block content %}


  <div class="row">

  <div class="col s12 m8 l6">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <div class="row">
          {% if field.field.widget.input_type == 'file' %}
            <div class="file-field input-field col s12 m12 l12 col">
              <div class="btn">
                <span>{{field.label}}</span>
                {{field}}
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
              </div>
            </div>
          {% else %}
            <div class="input-field col s12 m12 l12">
              {{field}}
              <label for="email" data-error="wrong" data-success="right">
                {{field.label}}
              </label>
            </div>
          {% endif %}

          {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
      {% endfor%}

      <div class="row">
        <div class="input-field col s12 m12 l12">
        <a class="btn red" href="{% url 'agency:list' %}">
          <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
        </a>
        <button type="submit" class="btn green">
          <i class="fa fa-fw fa-floppy-o" aria-hidden="true"></i> Salvar
        </button>
        </div>
      </div>
    </form>
  </div>

  </div>
{% endblock %}

{% block extra_js %}

  <script>
    $(document).ready(function() {
    });

    $('.datepicker').pickadate({
       selectMonths: true, // Creates a dropdown to control month
       selectYears: 15, // Creates a dropdown of 15 years to control year,
       today: 'Hoje',
       clear: 'Limpar',
       close: 'Fechar',
       closeOnSelect: false, // Close upon selecting a date,
       format: 'dd/mm/yyyy',
     });
  </script>

{% endblock %}

apps/client/templates/client/list.html
{% extends "components/base.html" %}

{% block content %}

  <div class="row">
    <form action="" method="get">
      <div class="row">
        {% for field in form_search %}
          <div class="input-field col s12 m3 l4">
            {{field}}
            <label for="{{field.auto_id}}">{{field.label}}</label>
          </div>
        {% endfor %}
      </div>
      <div class="input-field col s12 m2 l3">
        <button type="submit" class="btn green">
          <i class="fa fa-fw fa-search-o" aria-hidden="true"></i> Buscar
        </button>
      </div>
    </form>
  </div>

  <div class="row">
    <div class="col l12 m12 s12">

      <div class="row">
        <div class="table-responsive">
          <table class="table table-striped responsive-table">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>telefone</th>
                <th>Ações</th>
              </tr>
            </thead>
              <tbody>
                {% for c in clients %}
                <tr>
                  <td><a href='#'>{{c.name}}</a></td>
                  <td>{{c.email}}</td>
                  <td>{{c.fone}}</td>
                  <td>
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                    <a href="{% url 'client:detail' c.id %}" class="btn">
                      <i class="material-icons">remove_red_eye</i>
                    </a>
                    <a href="{% url 'client:edit' c.id %}" class="btn yellow">
                      <i class="material-icons">mode_edit</i>
                    </a>
                    <a href="{% url 'client:delete' c.id %}" class="btn red">
                      <i class="material-icons">clear</i>
                    </a>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>

  <div class="row">

    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="waves-effect" ><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
          <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
        {% endif %}
          <li class="">
              <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
          </li>
        {% if page_obj.has_next %}
            <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
          <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>

  <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large waves-effect waves-light pink" href="/clientes/novo/"><i class="material-icons">add</i></a>
  </div>

{% endblock %}