apps/outdoor/urls.py
from django.conf.urls import url
from apps.outdoor import views

app_name = 'outdoor'

urlpatterns = [
    url(r'novo/$',
        views.NewOutdoor.as_view(), name='new'),
    url(r'(?P<id>[\w_-]+)/editar/$',
        views.UpdateOutdoor.as_view(), name='edit'),
    url(r'(?P<pk>[\w_-]+)/delete/$',
        views.DeleteOutdoor.as_view(), name='delete'),
    url(r'(?P<pk>[\w_-]+)/email/add/$',
        views.OutdoorEmailAdd.as_view(), name='email'),
    url(r'(?P<pk>[\w_-]+)/email/clear/one/$',
        views.OutdoorEmailClearOne.as_view(), name='email-clear-one'),

    url(r'email/clear/all/$',
        views.OutdoorEmailClearAll.as_view(), name='email-clear'),

    url(r'email/send/$',
        views.OutdoorEmailSend.as_view(), name='email-send'),

    url(r'(?P<pk>[\w_-]+)/locar/$',
        views.LocaOutdoor.as_view(), name='locar'),

    url(r'(?P<pk>[\w_-]+)/convert/$',
        views.Convert.as_view(), name='convert'),


    url(r'(?P<pk>[\w_-]+)/reserva/$',
        views.ReserveOutdoor.as_view(), name='reserva'),

    url(r'(?P<pk>[\w_-]+)/detalhe/$',
        views.DetailOutdoor.as_view(), name='detail'),
    url(r'$', views.ListOutdoor.as_view(), name='list'),
]

floriano_outdoor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from apps.client import urls as client_urls
from apps.core import urls as core_urls
from apps.agency import urls as agency_urls
from apps.outdoor import urls as outdoors_urls
from apps.rent import urls as rent_urls
from apps.usuarios import urls as users_urls
from apps.reserve import urls as reserve_urls
from apps.cash import urls as cash_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^clientes/', include(client_urls)),
    url(r'^agencias/', include(agency_urls)),
    url(r'^outdoors/', include(outdoors_urls)),
    url(r'^locacao/', include(rent_urls)),
    url(r'^usuarios/', include(users_urls)),
    url(r'^reservas/', include(reserve_urls)),
    url(r'^caixa/', include(cash_urls)),
    url(r'^', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/outdoor/models.py
from django.db import models
from apps.core.models import SuperClass
from django.contrib.auth.models import User
from versatileimagefield.fields import VersatileImageField
from django.db.models import Q
from datetime import datetime


class Outdoor(SuperClass):
    """
        Código
        Agência (a ser escolhida entre as cadastradas)
        Tamanho Largura x Altura.
        Cidade
        Bairro
        Rua
        Ponto de Referencia
        Foto da placa
    """
    code = models.CharField(
        "Código", max_length=255, null=False, blank=False)
    cidade = models.CharField(
        "Cidade", max_length=255, null=False, blank=False)
    bairro = models.CharField(
        "Bairro", max_length=255, null=False, blank=False)
    rua = models.CharField(
        "Rua", max_length=255, null=True, blank=True)
    referencia = models.CharField(
        "Referência", max_length=255, null=True, blank=True)
    image = VersatileImageField(
        upload_to='outdoors/', default='outdoors/no-img.jpg')
    # imagem = VersatileImageField(
    #     'Imagem', upload_to='uploads/notice/%Y/%m/', null=True)
    agency = models.ForeignKey(
        'agency.Agency', blank=True, null=True, related_name='agency_outdoor')
    creator = models.ForeignKey(
        User, blank=True, null=True, related_name='creator_outdoor')

    class Meta:
        verbose_name = "Outdoor"
        verbose_name_plural = "Outdoors"
        ordering = ('code',)
        get_latest_by = '-created_at'

    @property
    def is_rent(self):
        start = datetime.now().date()
        query = Q(status=True)
        query.add(Q(end__gte=start), Q.AND)
        return self.outdoor_location.filter(query).exists()

    @property
    def is_reserved(self):
        start = datetime.now().date()
        query = Q(status=True)
        query.add(Q(end__gte=start), Q.AND)
        # query.add(Q(end__lte=stop), Q.AND)
        return self.outdoor_reserve.filter(query).exists()

    def __str__(self):
        return "%s - %s - %s" % (self.code, self.cidade, self.bairro)

apps/outdoor/forms.py
from django import forms
from apps.client.models import Client
from apps.agency.models import Agency
from apps.outdoor.models import Outdoor
from django.conf import settings
from django.db.models import Q
import datetime


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + datetime.timedelta(n)


class FormOutdoor(forms.Form):
    code = forms.CharField(
        label='Código', max_length=80, required=True,
        widget=forms.TextInput(attrs={'class': ''}))
    cidade = forms.CharField(
        label='Cidade', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    bairro = forms.CharField(
        label='Bairro', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    image = forms.FileField(
        label='Imagem', max_length=200, required=False,
        widget=forms.ClearableFileInput(attrs={'class': ''}))
    rua = forms.CharField(
        label='Rua', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    referencia = forms.CharField(
        label='Referência', required=False,
        widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))


class FormLocation(forms.Form):
    client = forms.ModelChoiceField(
        label='Cliente', queryset=Client.objects.all(),  required=False,
        widget=forms.Select(attrs={'class': ''}))
    agency = forms.ModelChoiceField(
        label='Agencia', queryset=Agency.objects.all(),  required=False,
        widget=forms.Select(attrs={'class': ''}))

    start = forms.DateField(
        label='Inicio', input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': ' datepicker'}))
    end = forms.DateField(
        label='Fim', input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': ' datepicker'}))
    outdoor = forms.IntegerField(
        label='', widget=forms.HiddenInput(), required=False)

    alert = forms.BooleanField(
        label='Aleta de Email', required=False, initial=False,
        widget=forms.CheckboxInput(attrs={'class': ''}))

    # cash
    cash = forms.BooleanField(
        label='Caixa', required=False, initial=False,
        widget=forms.CheckboxInput(attrs={'class': ''}))
    date = forms.DateField(
        label='Data', required=False,
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(
            attrs={'class': 'datepicker', 'readonly': True}))
    value = forms.DecimalField(
        label='Valor', required=False,
        widget=forms.NumberInput(attrs={'class': ''}))
    observation = forms.CharField(
        label='Descrição', required=False,
        widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))

    def clean(self):
        cleaned_data = super(FormLocation, self).clean()
        # today = datetime.date.today()
        data_start = cleaned_data['start']
        data_end = cleaned_data['end']
        outdoor_id = cleaned_data['outdoor']

        outdoor = Outdoor.objects.get(id=outdoor_id)

        if data_start >= data_end:
            self.add_error(
                'start', "Data de início menor que data final")

        else:
            for check_date in daterange(data_start, data_end):
                query = Q(status=True)
                query.add(
                    Q(start__lte=check_date) & Q(end__gte=check_date), Q.AND)
                if outdoor.outdoor_location.filter(query).exists():
                    self.add_error('end', "Outdoor locado nessa data")
                    break

            for check_date in daterange(data_start, data_end):
                query = Q(status=True)
                query.add(
                    Q(start__lte=check_date) & Q(end__gte=check_date), Q.AND)
                if outdoor.outdoor_reserve.filter(query).exists():
                    self.add_error('end', "Outdoor reservado nessa data")
                    break


class FormSearchOutdoor(forms.Form):
    STATUS_CHOICES = (
        ('0', 'Todos'),
        ('1', 'Disponível'),
        ('2', 'Reservado'),
        ('3', 'Locado'))
    term = forms.CharField(
        label='Busca', max_length=80, required=False,
        widget=forms.TextInput(attrs={'class': ''}))
    status = forms.ChoiceField(
        choices=STATUS_CHOICES, label="Estado",
        initial='0', widget=forms.Select(), required=False)


class FormReserve(forms.Form):
    client = forms.ModelChoiceField(
        label='Cliente', queryset=Client.objects.all(),  required=False,
        widget=forms.Select(attrs={'class': ''}))
    agency = forms.ModelChoiceField(
        label='Agencia', queryset=Agency.objects.all(),  required=False,
        widget=forms.Select(attrs={'class': ''}))
    start_date = forms.DateField(
        label='Inicio', input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': 'datepicker'}))
    end_date = forms.DateField(
        label='Fim', input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': 'datepicker'}))
    alert = forms.BooleanField(
        label='Aleta de Email', required=False, initial=False,
        widget=forms.CheckboxInput(attrs={'class': ''}))
    outdoor = forms.IntegerField(
        label='', widget=forms.HiddenInput(), required=False)

    def clean(self):
        cleaned_data = super(FormReserve, self).clean()
        today = datetime.date.today()
        data_start = cleaned_data['start_date']
        data_end = cleaned_data['end_date']
        outdoor_id = cleaned_data['outdoor']

        outdoor = Outdoor.objects.get(id=outdoor_id)

        if data_start >= data_end:
            self.add_error(
                'start_date', "Data de início menor que data final")
        # elif today <= data_start:
        #     self.add_error(
        #         'start_date', "Data de início menor que data atual")
        else:
            for check_date in daterange(data_start, data_end):
                query = Q(status=True)
                query.add(
                    Q(start__lte=check_date) & Q(end__gte=check_date), Q.AND)
                if outdoor.outdoor_location.filter(query).exists():
                    self.add_error('end_date', "Outdoor locado nessa data")
                    break

            for check_date in daterange(data_start, data_end):
                query = Q(status=True)
                query.add(
                    Q(start__lte=check_date) & Q(end__gte=check_date), Q.AND)
                if outdoor.outdoor_reserve.filter(query).exists():
                    self.add_error('end_date', "Outdoor reservado nessa data")
                    break

apps/outdoor/templates/outdoor/delete.html
{% extends "components/base.html" %}

{% block content %}

  <div class="row">
    <div class="col s12 m12 l12">
      <h3>Você deseja deletar o outdoor  "{{ object }}" ?</h3>
      <form method="post" action="">
        {% csrf_token %}
        <br>
        <div class="row">
          <a class="btn red" href="{% url 'outdoor:list' %}">
            <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
          </a>
          <button type="submit" value="" class="btn green" >
            <i class="fa fa-fw fa-trash" aria-hidden="true"></i> Deletar
          </button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/outdoor/templates/outdoor/detail.html
{% extends "components/base.html" %}

{% block content %}

<div class="row">
  <h1 class="page-header">{{object.name}} </h1>
</div>


<div class="row">
  <div class="col s12">
    <div class="row">

      <div class="col s12 m12 l6">
        <div class="card">
          <div class="card-image">
            <img src="{% if object.image %}{{object.image.url}}{% else %}/static/img/outdoor.png{% endif %}">
            <span class="card-title">{{object.code}}</span>
          </div>
          <div class="card-content">
            <p><b>Cidade:</b> {{object.cidade}}</p>
            <p><b>Bairro:</b> {{object.bairro}}</p>
            <p><b>Referencia:</b> {{object.referencia}}</p>
          </div>
          <div class="card-action">
            {# <a href="#">This is a link</a>#}
          </div>
        </div>
      </div>

      <div class="col s12 m12 l6">
        <h5>Locações</h5>
        <table class="table table-condensed table-hover" id='table_service'>
            <thead>
              <tr>
                <th>Cliente</th>
                <th>Agência</th>
                <th>Periodo</th>
              </tr>
            </thead>
            <tbody>
              {% for loc in  locations %}
              <tr>
                <td>{{loc.client.name}}</td>
                <td>{{loc.agency.name}}</td>
                <td>{{loc.start|date:"d/m/y"}} - {{loc.end|date:"d/m/y"}}</td>
              </td>
              {% endfor %}
            </tbody>
            <tfoot>
              <div class="row">
                {% if locations.has_other_pages %}
                <ul class="pagination">
                  {% if locations.has_previous %}
                    <li class="waves-effect" ><a href="?page_l={{ locations.previous_page_number }}&page_r={{ reserves.number }}"><i class="material-icons">chevron_left</i></a></li>
                  {% else %}
                    <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
                  {% endif %}
                    <li class="">
                        <span>Página {{ locations.number }} de {{ locations.paginator.num_pages }}.</span>
                    </li>
                  {% if locations.has_next %}
                      <li class="waves-effect"><a href="?page_l={{ locations.next_page_number }}&page_r={{ reserves.number }}"><i class="material-icons">chevron_right</i></a></li>
                  {% else %}
                    <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
                  {% endif %}
                </ul>
                {% endif %}
              </div>
            </tfoot>
          </table>
          <h5>Reservas</h5>
          <table class="table table-condensed table-hover" id='table_service'>
            <thead>
              <tr>
                <th>Agência</th>
                <th>Cliente</th>
                <th>Periodo</th>
              </tr>
            </thead>
            <tbody>
              {% for res in  reserves %}
              <tr>
                <td>{{res.agency.name}}</td>
                <td>{{res.client.name}}</td>
                <td>{{res.start|date:"d/m/y"}} - {{loc.end|date:"d/m/y"}}</td>
              </td>
              {% endfor %}

            </tbody>
            <tfoot>
              <div class="row">
                {% if reserves.has_other_pages %}
                  <ul class="pagination">
                    {% if reserves.has_previous %}
                      <li class="waves-effect" ><a href="?page_r={{ reserves.previous_page_number }}&page_l={{ locations.number }}"><i class="material-icons">chevron_left</i></a></li>
                    {% else %}
                      <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
                    {% endif %}
                      <li class="">
                          <span>Página {{ reserves.number }} de {{ reserves.paginator.num_pages }}.</span>
                      </li>
                    {% if reserves.has_next %}
                        <li class="waves-effect"><a href="?page_r={{ reserves.next_page_number }}&page_l={{ locations.number }}"><i class="material-icons">chevron_right</i></a></li>
                    {% else %}
                      <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
                    {% endif %}
                  </ul>
                {% endif %}
              </div>
            </tfoot>
          </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extra_js %}

{% endblock %}

apps/outdoor/templates/outdoor/form.html
{% extends "components/base.html" %}

{% block content %}

<div class="row">
  <div class="col s12 m8 l6">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <div class="row">
          {% if field.field.widget.input_type == 'file' %}
            <div class="file-field input-field col s12 m12 l12 col">
              <div class="btn">
                <span>{{field.label}}</span>
                {{field}}
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
              </div>
            </div>
          {% elif field.field.widget.input_type == 'checkbox' %}
            <div class="col s12 m12 l6">
              {{field}}
              <label for="{{field.auto_id}}">
                {{field.label}}
              </label>
            </div>
          {% else %}
            <div class="input-field col s12 m12 l12">
              {{field}}
              <label for="email" data-error="wrong" data-success="right">
                {{field.label}}
              </label>
            </div>
          {% endif %}

          {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
      {% endfor%}

      <div class="row">
        <div class="input-field col s12 m12 l12">
        <a class="btn red" href="{% url 'outdoor:list' %}">
          <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
        </a>
        <button type="submit" class="btn green">
          <i class="fa fa-fw fa-floppy-o" aria-hidden="true"></i> Salvar
        </button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

{% block extra_js %}

  <script>
    $(document).ready(function() {
    });

    $('.datepicker').pickadate({
       selectMonths: true, // Creates a dropdown to control month
       selectYears: 15, // Creates a dropdown of 15 years to control year,
       today: 'Today',
       clear: 'Clear',
       close: 'Ok',
       closeOnSelect: false, // Close upon selecting a date,
       format: 'dd/mm/yyyy',
     });

     $('#id_cash').change(function(){
       if ($('#id_cash').is(":checked")) {
         $('#id_date').parent().show();
         $('#id_value').parent().show();
         $('#id_observation').parent().show();
       } else {
         $('#id_date').val('');
         $('#id_date').parent().hide();
         $('#id_value').val('');
         $('#id_value').parent().hide();
         $('#id_observation').val('');
         $('#id_observation').parent().hide();
       }
     });

     $('#id_cash').trigger('change');
  </script>

{% endblock %}

apps/outdoor/templates/outdoor/list.html
{% extends "components/base.html" %}

{% load outdoor_tags %}

{% block content %}

  <div class="row">
  <div class="col l12 m12 s12">
    <div class="row">
      <form action="" method="get">
        <div class="row">
          {% for field in form_search %}
            <div class="input-field col s12 m3 l4">
              {{field}}
              <label for="{{field.auto_id}}">{{field.label}}</label>
            </div>
          {% endfor %}
        </div>
        <div class="input-field col s12 m2 l3">
          <button type="submit" class="btn green">
            <i class="fa fa-fw fa-search-o" aria-hidden="true"></i> Buscar
          </button>
        </div>
      </form>
    </div>

    <div class="row">
      {% for out in outdoors  %}
        <div class="col l4 m6 s12">
          <div class="card z-depth-2 sticky-action">
            <div class="card-image">
              <img src="{% if out.image %}{{out.image.crop.340x185.url}}{% else %}/static/img/outdoor.png{% endif %}">
              <span class="black-text card-title text-darken-2"></span>
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">{{out.code}}<i class="material-icons right">more_vert</i>
              </span>

              <div class="row">
                <div class="col m5">
                  {% if out.is_rent %}
                    <p><span class="white-text badge red" >Locado</span></p>
                  {% else %}
                    <p><span class="white-text badge green" >Dísponivel</span></p>
                  {% endif %}
                </div>
                <div class="col m5">
                  {% if out.is_reserved %}
                    <p><span class="white-text badge blue" style="right: 80px;">Reservado</span></p>
                  {% endif %}
                </div>
              </div>

            </div>
            <div class="card-action">
              <a class="waves-effect waves-light tooltipped" href="{% url 'outdoor:detail' out.id %}"
                data-position="bottom" data-delay="50" data-tooltip="Ver"
              >
                <i class="material-icons">remove_red_eye</i>
              </a>
              <a class="waves-effect waves-light tooltipped" href="{% url 'outdoor:edit' out.id %}"
                data-position="bottom" data-delay="50" data-tooltip="Editar">
                  <i class="material-icons">create</i>
              </a>
              {% if not out.is_rent %}
              <a class="waves-effect waves-light tooltipped" href="{% url 'outdoor:locar' out.id %}" data-position="bottom" data-delay="50" data-tooltip="Locar">
                <i class="material-icons">event</i>
              </a>
              {% endif %}
              <a class="waves-effect waves-light tooltipped" href="{% url 'outdoor:reserva' out.id %}" data-position="bottom" data-delay="50" data-tooltip="Reservar">
                <i class="material-icons">event_note</i>
              </a>
              <a class="waves-effect waves-light tooltipped" href="{% url 'outdoor:email' out.id %}"
                data-position="bottom" data-delay="50" data-tooltip="Email">
                <i class="material-icons">mail</i>
              </a>
              <a class="waves-effect waves-light tooltipped" href="{% url 'outdoor:delete' out.id %}"
                  data-position="bottom" data-delay="50" data-tooltip="Delete">
                <i class="material-icons">clear</i>
              </a>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4">
                {{out.code}}
                <i class="material-icons right">close</i>
              </span>
              <p>{{out.referencia}}</p>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>

  </div>
  </div>

  <div class="row">

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="waves-effect" ><a href="?{% url_replace page=page_obj.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
      {% else %}
        <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}
        <li class="">
            <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
        </li>
      {% if page_obj.has_next %}
          <li class="waves-effect"><a href="?{% url_replace page=page_obj.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
      {% else %}
        <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
      {% endif %}
    </ul>
  {% endif %}
  </div>


  <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large waves-effect waves-light pink" href="/outdoors/novo/"><i class="material-icons">add</i></a>
  </div>

  {% comment %}


  <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large pink waves-effect waves-light">
      <i class="large material-icons">add</i>
    </a>

    <ul>
      <li>
        <a class="btn-floating red"><i class="material-icons">note_add</i></a>
        <a href="" class="btn-floating fab-tip">Add a note</a>
      </li>

      <li>
        <a class="btn-floating yellow darken-1"><i class="material-icons">add_a_photo</i></a>
        <a href="" class="btn-floating fab-tip">Add a photo</a>
      </li>

      <li>
        <a class="btn-floating green"><i class="material-icons">alarm_add</i></a>
        <a href="" class="btn-floating fab-tip">Add an alarm</a>
      </li>

      <li>
        <a class="btn-floating blue"><i class="material-icons">vpn_key</i></a>
        <a href="" class="btn-floating fab-tip">Add a master password</a>
      </li>
    </ul>
  </div>

  {% endcomment %}
{% endblock %}